### PR TITLE
Added support to encrypt and decrypt DateTime, JSON and array data types

### PR DESCRIPTION
**Pull request by r3hp1c**

### CODE REVIEW

**Comment by r3hp1c** [comment]
@cs-akash-jarad I do not just want to merge this one, it is a little bigger than the others I did. Please review and merge if you are happy.

**Comment by cs-akash-jarad** [comment]
sure will check. i ll be able to review and merge this weekend.

**Comment by r3hp1c** [comment]
@cs-akash-jarad any chance that you will be able to get to this soon?

**Review by Zombaya — CHANGES_REQUESTED** [review]
I like the idea to support other types than just strings.  

What I would change though, is leveraging `\Doctrine\DBAL\Types\Type::getType()` and it's conversions from and to SQL-representation (which usually are strings) so that we can support all types of already known doctrine-types, including custom ones defined by our users.

This way we can avoid doing the conversion from PHP to string and back ourselves.

The only thing we would need to do, is choose an appropriate Platform to use for our conversions.

An demo-implementation can be found somewhere in my code-review-comments.

I've also noted some places where I'd do some stricter compares.

**Comment by r3hp1c** [comment]
@Zombaya I implemented your suggestion of using \Doctrine\DBAL\Types\Type::getType() instead of doing the conversions directly. Note that I used the entity manager getConnection and the connection getDatabasePlatform instead of always just using the MySql Platform. 

If you approve, then we could merge and finish your pull request to add support for Symfony 7 #28 and the non-breaking changes in #27.

Once we have all those changes done, I want to release version 5.3.2 and create 2 branches 5.x and 6.x. In the 6.x branch I would like to start implementing all the breaking changes.  I do have an idea I would like to try that I think could possibly make the bundle a little faster and use less memory, but will need to get there to try it out and confirm.

**Comment by Zombaya** [comment]
Firstly, sorry to go so long without responding. We had a very hectic period before Christmas and after the holidays and I had little energy left after work to work on open source.

The code looks good to me.

I would however rethink fetching the platform from the connection. I feel it would be better to use a fixed platform so that:

1. a user could migrate from database-platform. If the encoding/decoding differs between the original platform and the new platform, there will be data-corruption
2. if a bug ever pops up regarding this type of encoding/decoding, we can be pretty certain which platform was used and how the data was encoded.

But code-wise, everything looks good to me.

**Comment by r3hp1c** [comment]
> Firstly, sorry to go so long without responding. We had a very hectic period before Christmas and after the holidays and I had little energy left after work to work on open source.
> 
> The code looks good to me.
> 
> I would however rethink fetching the platform from the connection. I feel it would be better to use a fixed platform so that:
> 
> 1. a user could migrate from database-platform. If the encoding/decoding differs between the original platform and the new platform, there will be data-corruption
> 2. if a bug ever pops up regarding this type of encoding/decoding, we can be pretty certain which platform was used and how the data was encoded.
> 
> But code-wise, everything looks good to me.

Have invited you again. Thanks for the willingness to assist and keep the bundle alive.

I see your point about the possible data corruption between database platforms, but will that not possibly be an issue as well if we force the use of a mismatching platform?

**Comment by r3hp1c** [comment]
@Zombaya think we should merge #28 before we merge this one as Symfony 7 support is probably more important than adding support for new types.
I did make the change to use a fixed platform as suggested.

**Pull request merged**
