### PR TITLE
Fix compatibility with "doctrine/orm" 3.x

### LINKED ISSUE #46: PHPStan fails with "Class Doctrine\ORM\Mapping\ClassMetadataInfo not found." when "Static Analysis" job is set to higher that php version 8.0

### PR DESCRIPTION
**Pull request by phansys**
Fixes #46.

The SCA is also restored for the `tests/` directory.

### CODE REVIEW

**Comment by Zombaya** [comment]
You're on a roll, nice work :+1:.

I don't see anything wrong with this PR, it can be merged as far as I am concerned.  

Just for my understanding/expanding my knowledge: is there any particular reason why you changed all the assertions from `$this->assert...` to `static::assert...`?

I always believed it didn't really matter what you use and I personally prefer the `$this->assert...`, but that's more habitually than anything else.

**Comment by phansys** [comment]
Hey @Zombaya!
The reason to change the calls to `assert*()` to a static binding is the need to respect the definition for these methods, which are in fact declared as [`static`](https://www.php.net/manual/en/language.oop5.static.php#language.oop5.static.methods).
See: https://github.com/sebastianbergmann/phpunit/blob/9b98888a90c39dc922f01e6d3a34bc077bac3460/src/Framework/Assert.php#L1709.

**Comment by phansys** [comment]
Just for the records: https://phpstan.org/r/13a044ac-d11d-4fe5-8316-e0fcbb47404d.

**Comment by Zombaya** [comment]
As it's already merged, I would keep everything as it is, but otherwise I would have suggested to keep the unit-tests as they were, or if we were to change them, to have that done in a separate commit and pull-request as it's not really related to the problem which was solved in this PR.

Additionally, I think I would have opted to keep the assertions as is, as the documentation of phpunit uses the style of `$this->assert...` as well.

From the documentation: 
> A common question, especially from developers new to PHPUnit, is whether using `$this->assertTrue()` or `self::assertTrue()`, for instance, is “the right way” to invoke an assertion. The short answer is: there is no right way. And there is no wrong way, either. It is a matter of personal preference.
> 
> For most people it just “feels right” to use `$this->assertTrue()` because the test method is invoked on a test object. The fact that the assertion methods are declared static allows for (re)using them outside the scope of a test object. Lastly, the global function wrappers allow developers to type less characters (`assertTrue()` instead of `$this->assertTrue()` or `self::assertTrue()`).

Having said all that, I would not spend more time on it for the time being, as it works either way.

**Pull request merged**
